version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2021.04

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: build
          command: echo build
  deploy_to_stg:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: echo deploy to stg
  deploy_to_prd:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: echo deploy to prd

workflows:
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^release_[0-9]+$/
      - deploy_to_stg:
          requires:
            - build
      - deploy_to_prd:
          requires:
            - build
          filters:
            tags:
              only: /^release_[0-9]+$/
            branches:
              ignore: /.*/
