version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2021.04

jobs:
  deploy_to_stg:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: echo deploy to stg
  deploy_to_prd:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy
          command: echo deploy to prd

workflows:
  deploy:
    jobs:
      - deploy_to_stg
      - deploy_to_prd:
          filters:
            tags:
              only: /release/
            branches:
              ignore: /.*/
