version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2021.04

commands:
  set_env:
    steps:
      - run:
          name: set environment
          command: . .circleci/set_env.sh

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - set_env
      - run:
          name: build
          command: echo CIRCLE_TAG ${CIRCLE_TAG} CIRCLE_BRANCH ${CIRCLE_BRANCH}
  deploy:
    <<: *defaults
    steps:
      - checkout
      - set_env
      - run:
          name: deploy
          command: echo CIRCLE_TAG ${CIRCLE_TAG} CIRCLE_BRANCH ${CIRCLE_BRANCH}

workflows:
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^release_[0-9]+$/
      - approval:
           type: approval
           requires:
             - build
           filters:
             tags:
               only: /^release_[0-9]+$/
             branches:
               ignore: /.*/
      - deploy:
          requires:
            - build
            - approval
          filters:
            tags:
              only: /^release_[0-9]+$/
